-- -----------------------------------------------------
-- Animations
-- name "Default"
-- -----------------------------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    animations = {
        enabled = false,
    },
})
