-- -----------------------------------------------------
-- General window decoration
-- name: "Rounding All Blur No Shadows"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,
        blur = {
            enabled = false,
        },
        shadow = {
            enabled = false,
        },
    },
})
