# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------
cursor {
    no_hardware_cursors = false
}

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24
# Default settings in myhypr.conf
