-- -----------------------------------------------------
-- Environment Variables
-- name: "Default"
-- -----------------------------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")
hl.config({
    cursor = {
        no_hardware_cursors = false,
    },
    -- Default settings in myhypr.conf
})
