-- -----------------------------------------------------
-- Environment Variables
-- name: "KVM"
-- -----------------------------------------------------

-- Default settings in myhypr.conf

-- KVM Environment
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("WLR_RENDERER_ALLOW_SOFTWARE", "1")
-- env = LIBGL_ALWAYS_SOFTWARE,1
