-- -----------------------------------------------------
-- Monitor Setup
-- name: "1366x768"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "1366x768",
    position = "auto",
    scale = "1",
})
