-- -----------------------------------------------------
-- Monitor Setup
-- name: "1600x900"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "1600x900",
    position = "auto",
    scale = "1",
})
