-- -----------------------------------------------------
-- Monitor Setup
-- name: "1920x1200"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "1920x1200",
    position = "auto",
    scale = "1",
})
