-- -----------------------------------------------------
-- Monitor Setup
-- name: "2560x1440@120x125"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "2560x1440@120",
    position = "auto",
    scale = "1.25",
})
