-- -----------------------------------------------------
-- Monitor Setup
-- name: "3440x1440"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "3440x1440",
    position = "auto",
    scale = "1",
})
