-- -----------------------------------------------------
-- Monitor Setup
-- name: "Highres"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "highres",
    position = "auto",
    scale = "1",
})
