-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local home = os.getenv("HOME")

local function load_generated(name, fallback)
    local generated = io.open(home .. "/.config/hypr/" .. name .. ".lua", "r")
    if generated then
        generated:close()
        require(name)
    else
        require(fallback)
    end
end

-- nwg-displays owns these ignored host-local files. A portable default keeps
-- this variation valid before the first layout is generated.
load_generated("monitors", "conf.monitors.default")
load_generated("workspaces", "conf.workspaces.default")
