-- -----------------------------------------------------
-- Layouts
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
    master = {
        -- Commented out due to compatibility reasons
        -- new_status = master
    },
    binds = {
        workspace_back_and_forth = false,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
})
