
$background = rgba(f6fafeff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(eef1f6ff)

$inverse_primary = rgba(94cdf6ff)

$inverse_surface = rgba(2d3135ff)

$on_background = rgba(181c20ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(001e2eff)

$on_primary_fixed = rgba(001e2eff)

$on_primary_fixed_variant = rgba(004c6dff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(0b1d29ff)

$on_secondary_fixed = rgba(0b1d29ff)

$on_secondary_fixed_variant = rgba(384956ff)

$on_surface = rgba(181c20ff)

$on_surface_variant = rgba(41484dff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(1f1635ff)

$on_tertiary_fixed = rgba(1f1635ff)

$on_tertiary_fixed_variant = rgba(4b4163ff)

$outline = rgba(71787eff)

$outline_variant = rgba(c1c7ceff)

$primary = rgba(246488ff)

$primary_container = rgba(c8e6ffff)

$primary_fixed = rgba(c8e6ffff)

$primary_fixed_dim = rgba(94cdf6ff)

$scrim = rgba(000000ff)

$secondary = rgba(4f606eff)

$secondary_container = rgba(d2e5f5ff)

$secondary_fixed = rgba(d2e5f5ff)

$secondary_fixed_dim = rgba(b7c9d8ff)

$shadow = rgba(000000ff)

$source_color = rgba(5b8bacff)

$surface = rgba(f6fafeff)

$surface_bright = rgba(f6fafeff)

$surface_container = rgba(ebeef3ff)

$surface_container_high = rgba(e5e8edff)

$surface_container_highest = rgba(dfe3e7ff)

$surface_container_low = rgba(f1f4f9ff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d7dadfff)

$surface_tint = rgba(246488ff)

$surface_variant = rgba(dde3eaff)

$tertiary = rgba(63597cff)

$tertiary_container = rgba(e9ddffff)

$tertiary_fixed = rgba(e9ddffff)

$tertiary_fixed_dim = rgba(cdc0e9ff)


