--  _   _                  _                 _
-- | | | |_   _ _ __  _ __| | __ _ _ __   __| |
-- | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
-- |  _  | |_| | |_) | |  | | (_| | | | | (_| |
-- |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
--        |___/|_|
--
-- -----------------------------------------------------
-- Keep machine-specific changes in local.lua and use the selector files under
-- conf/ for portable configuration variations.

-- writes a one-line legacy selector such as `source = .../windows/default.conf`;
-- this helper reads that choice and loads its converted Lua sibling.
-- The selector files intentionally remain one-line Hyprlang files so both the
-- local settings UI and the converted Lua configuration can share them.
-- writes a one-line legacy selector such as `source = .../windows/default.conf`;
-- this helper reads that choice and loads its converted Lua sibling.
function load_legacy_variant(selector, category, fallback)
    local home = os.getenv("HOME")
    local path = selector:gsub("^~", home)
    local file = io.open(path, "r")
    local name = nil
    if file then
        local content = file:read("*all")
        file:close()
        name = content:match("/" .. category .. "/([^/%s]+)%.conf")
    end
    if not name or not name:match("^[%w_@%-]+$") then
        name = fallback
    end
    local module = io.open(home .. "/.config/hypr/conf/" .. category .. "/" .. name .. ".lua", "r")
    if module then
        module:close()
    else
        name = fallback
    end
    require("conf." .. category .. "." .. (name or fallback))
end

-- -----------------------------------------------------
-- Monitor
-- -----------------------------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/conf/monitor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.monitor")

-- -----------------------------------------------------
-- Cursor
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/cursor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.cursor")

-- -----------------------------------------------------
-- Environment
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/environment.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.environment")

-- -----------------------------------------------------
-- Keyboard
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/keyboard.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.keyboard")

-- -----------------------------------------------------
-- Load color file
-- -----------------------------------------------------
-- Source: ~/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")
color8 = primary
color11 = on_surface

-- -----------------------------------------------------
-- Autostart
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.autostart")

-- -----------------------------------------------------
-- Load configuration files
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/window.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.window")
-- Source: ~/.config/hypr/conf/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.decoration")
-- Source: ~/.config/hypr/conf/layout.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.layout")
-- Source: ~/.config/hypr/conf/workspace.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.workspace")
-- Source: ~/.config/hypr/conf/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.misc")
-- Source: ~/.config/hypr/conf/keybinding.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.keybinding")
-- Source: ~/.config/hypr/conf/windowrule.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.windowrule")

-- -----------------------------------------------------
-- Animation
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/animation.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.animation")

-- -----------------------------------------------------
-- Environment for xdg-desktop-portal-hyprland
-- -----------------------------------------------------
-- -----------------------------------------------------
-- MyHyprlandRice desktop integration
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/myhypr.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.myhypr")

-- -----------------------------------------------------
-- Custom
-- -----------------------------------------------------
-- Source: ~/.config/hypr/conf/custom.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("conf.custom")

-- Machine-specific monitors, input devices, and private commands belong in
-- ~/.config/hypr/local.lua. The file is intentionally ignored by Git/Stow.
local local_config = os.getenv("HOME") .. "/.config/hypr/local.lua"
local local_file = io.open(local_config, "r")
if local_file then
    local_file:close()
    require("local")
end

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/myhypr/scripts/start-session-services.sh")
    hl.exec_cmd("quickshell -p ~/.config/quickshell/shell.qml")
end)
