-- -----------------------------------------------------
-- General window layout and colors
-- name: "Default"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = color11,
            inactive_border = color8,
        },
        layout = "dwindle",
        resize_on_border = true,
    },
})
