-- -----------------------------------------------------
-- General window layout and colors
-- name: "Default"
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 20,
        border_size = 1,
        col = {
            active_border = { colors = { color8, on_primary }, angle = 90 },
            inactive_border = on_primary,
        },
        layout = "dwindle",
        resize_on_border = true,
    },
})
