--    ___       __           __           __
--   / _ |__ __/ /____  ___ / /____ _____/ /_
--  / __ / // / __/ _ \(_-</ __/ _ `/ __/ __/
-- /_/ |_\_,_/\__/\___/___/\__/\_,_/_/  \__/
--

-- Start Listeners
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Start Polkit

-- Load Wallpaper

-- Load Notification Daemon

-- Load GTK settings

-- Using hypridle to start hyprlock

-- Load cliphist history

-- Show the local welcome panel once

-- Start autostart cleanup

-- Start the Top Bar (Waybar)

-- Start the Bottom Dock

-- Start the Wallpaper & Notifications

hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/bin/bash ~/.config/myhypr/listeners.sh --startall")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("/usr/bin/bash ~/.config/hypr/scripts/wallpaper-restore.sh")
    hl.exec_cmd("/usr/bin/swaync")
    hl.exec_cmd("/usr/bin/bash ~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("/usr/bin/hypridle")
    hl.exec_cmd("/usr/bin/wl-paste --watch /usr/bin/cliphist store")
    hl.exec_cmd("/usr/bin/bash ~/.config/myhypr/scripts/myhypr-autostart.sh")
    hl.exec_cmd("/usr/bin/bash ~/.config/hypr/scripts/cleanup.sh")
    hl.exec_cmd("/usr/bin/bash ~/.config/waybar/launch.sh")
    hl.exec_cmd("/usr/bin/bash ~/.config/nwg-dock-hyprland/launch.sh")
end)
