-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/conf/windows/default.conf — convert this file to Lua and ensure it is on Lua's package.path.
load_legacy_variant("~/.config/hypr/conf/window.conf", "windows", "default")
