-- -----------------------------------------------------
-- Window rules
-- -----------------------------------------------------

-- idleinhibit
-- windowrule = match:class = ([window]), idleinhibit = fullscreen # Available modes: none, always, focus, fullscreen

--xwayland related rules
-- when moving objects in resolve a large border is produced
-- This rule prevents that and serves as a template for any problematic xwayland apps
-- windowrule = noblur, class:^(\bresolve\b)$, xwayland:1
-- This is a general rule for xwayland apps but can have other consequences
-- for one user it impacted EMACs so it's disabled by default
-- It's here as a reference or for quick triage of xwayland ap
--windowrule = noblur, xwayland:1

-- New Hyprland 0.53+ Syntax
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "satty-editor",
    match = {
        class = "^(com.gabm.satty)$",
    },
    float = true,
    center = true,
    size = "1200 800",
    pin = true,
})
